/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Neg #(
    parameter Bits = 1
)
(
      input signed [(Bits-1):0] in,
      output signed [(Bits-1):0] out
);
    assign out = -in;
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module CompUnsigned #(
    parameter Bits = 1
)
(
    input [(Bits -1):0] a,
    input [(Bits -1):0] b,
    output \> ,
    output \= ,
    output \<
);
    assign \> = a > b;
    assign \= = a == b;
    assign \< = a < b;
endmodule


module DIG_Mul_unsigned #(
    parameter Bits = 1
)
(
    
      input [(Bits-1):0] a,
      input [(Bits-1):0] b,
      output [(Bits*2-1):0] mul
    
);
    assign mul = a * b;
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule


module DIG_BitExtender #(
    parameter inputBits = 2,
    parameter outputBits = 4
)
(
    input [(inputBits-1):0] in,
    output [(outputBits - 1):0] out
);
    assign out = {{(outputBits - inputBits){in[inputBits - 1]}}, in};
endmodule




module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module Noise_Gate (
  input [15:0] audio_in,
  input clk,
  output [15:0] \output 
);
  wire s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire s3;
  wire s4;
  wire [10:0] s5;
  wire [10:0] s6;
  wire s7;
  wire [10:0] s8;
  wire [10:0] s9;
  wire [15:0] s10;
  wire [31:0] s11;
  wire s12;
  wire [10:0] s13;
  wire s14;
  DIG_Neg #(
    .Bits(16)
  )
  DIG_Neg_i0 (
    .in( audio_in ),
    .out( s1 )
  );
  assign s0 = audio_in[15];
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( s0 ),
    .in_0( audio_in ),
    .in_1( s1 ),
    .out( s2 )
  );
  // Attack
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i2 (
    .a( s2 ),
    .b( 16'b1111101000 ),
    .\> ( s3 )
  );
  // Release
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i3 (
    .a( s2 ),
    .b( 16'b111110100 ),
    .\< ( s4 )
  );
  // volume
  DIG_Mul_unsigned #(
    .Bits(16)
  )
  DIG_Mul_unsigned_i4 (
    .a( s10 ),
    .b( s2 ),
    .mul( s11 )
  );
  assign s7 = ~ (s3 | ~ (s4 | s7));
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i5 (
    .sel( s7 ),
    .in_0( 11'b1010 ),
    .in_1( 11'b11111110110 ),
    .out( s8 )
  );
  assign \output  = s11[25:10];
  // step adder
  DIG_Add #(
    .Bits(11)
  )
  DIG_Add_i6 (
    .a( s6 ),
    .b( s8 ),
    .c_i( 1'b0 ),
    .s( s9 )
  );
  // extender
  DIG_BitExtender #(
    .inputBits(11),
    .outputBits(16)
  )
  DIG_BitExtender_i7 (
    .in( s9 ),
    .out( s10 )
  );
  // check gain max
  CompUnsigned #(
    .Bits(11)
  )
  CompUnsigned_i8 (
    .a( 11'b10000000000 ),
    .b( s9 ),
    .\> ( s12 )
  );
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i9 (
    .sel( s12 ),
    .in_0( 11'b10000000000 ),
    .in_1( s9 ),
    .out( s13 )
  );
  // check gain min
  CompUnsigned #(
    .Bits(11)
  )
  CompUnsigned_i10 (
    .a( 11'b1100110 ),
    .b( s13 ),
    .\< ( s14 )
  );
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i11 (
    .sel( s14 ),
    .in_0( 11'b1100110 ),
    .in_1( s13 ),
    .out( s5 )
  );
  // gain
  DIG_Register_BUS #(
    .Bits(11)
  )
  DIG_Register_BUS_i12 (
    .D( s5 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( s6 )
  );
endmodule
