// ============================================================================
// Noise Gate Effect Module - Corrected Version
// ============================================================================
// Generated by Digital simulator, modified for proper port naming
//
// IMPORTANT: This file requires digital_utils.v with shared utility modules
//
// Implements adaptive noise gate with attack/release thresholds
// ============================================================================

module noise_gate (
  input wire reset,
  input clk,
  input signed [15:0] audio_in,
  output [15:0] audio_out
);
  wire s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire s3;
  wire s4;
  wire [10:0] s5;
  wire [10:0] s6;
  reg s7;
  wire [10:0] s8;
  wire [10:0] s9;
  wire [15:0] s10;
  wire [31:0] s11;
  wire s12;
  wire [10:0] s13;
  wire s14;
  // Unused outputs from utility modules
  wire unused_comp_eq0, unused_comp_lt0, unused_comp_gt1, unused_comp_eq1;
  wire unused_comp_eq2, unused_comp_lt2, unused_comp_gt3, unused_comp_eq3;
  wire unused_add_co;
  
  DIG_Neg #(
    .Bits(16)
  )
  DIG_Neg_i0 (
    .in( audio_in ),
    .out( s1 )
  );
  assign s0 = audio_in[15];
  Mux_2x1_NBits #(
    .Bits(16)
  )
  Mux_2x1_NBits_i1 (
    .sel( s0 ),
    .in_0( audio_in ),
    .in_1( s1 ),
    .out( s2 )
  );
  // Attack
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i2 (
    .a( s2 ),
    .b( 16'b1111101000 ),
    .\> ( s3 ),
    .\= ( unused_comp_eq0 ),
    .\< ( unused_comp_lt0 )
  );
  // Release
  CompUnsigned #(
    .Bits(16)
  )
  CompUnsigned_i3 (
    .a( s2 ),
    .b( 16'b111110100 ),
    .\> ( unused_comp_gt1 ),
    .\= ( unused_comp_eq1 ),
    .\< ( s4 )
  );
  // volume
  DIG_Mul_unsigned #(
    .Bits(16)
  )
  DIG_Mul_unsigned_i4 (
    .a( s10 ),
    .b( s2 ),
    .mul( s11 )
  );
  reg s7;  // Changed to reg to break combinational loop
  ...
  // Gate state machine with proper sequential logic
  always @(posedge clk or posedge reset) begin
    if (reset) begin
      s7 <= 1'b0;
    end else begin
      if (s3) begin
        s7 <= 1'b1;
      end else if (s4) begin
        s7 <= 1'b0;
      end
    end
  end
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i5 (
    .sel( s7 ),
    .in_0( 11'b1010 ),
    .in_1( 11'b11111110110 ),
    .out( s8 )
  );
  assign audio_out = s11[25:10];
  // step adder
  DIG_Add #(
    .Bits(11)
  )
  DIG_Add_i6 (
    .a( s6 ),
    .b( s8 ),
    .c_i( 1'b0 ),
    .s( s9 ),
    .c_o( unused_add_co )
  );
  // extender
  DIG_BitExtender #(
    .inputBits(11),
    .outputBits(16)
  )
  DIG_BitExtender_i7 (
    .in( s9 ),
    .out( s10 )
  );
  // check gain max
  CompUnsigned #(
    .Bits(11)
  )
  CompUnsigned_i8 (
    .a( 11'b10000000000 ),
    .b( s9 ),
    .\> ( s12 ),
    .\= ( unused_comp_eq2 ),
    .\< ( unused_comp_lt2 )
  );
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i9 (
    .sel( s12 ),
    .in_0( 11'b10000000000 ),
    .in_1( s9 ),
    .out( s13 )
  );
  // check gain min
  CompUnsigned #(
    .Bits(11)
  )
  CompUnsigned_i10 (
    .a( 11'b1100110 ),
    .b( s13 ),
    .\> ( unused_comp_gt3 ),
    .\= ( unused_comp_eq3 ),
    .\< ( s14 )
  );
  Mux_2x1_NBits #(
    .Bits(11)
  )
  Mux_2x1_NBits_i11 (
    .sel( s14 ),
    .in_0( 11'b1100110 ),
    .in_1( s13 ),
    .out( s5 )
  );
  // gain
  DIG_Register_BUS #(
    .Bits(11)
  )
  DIG_Register_BUS_i12 (
    .D( s5 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( s6 )
  );
endmodule
