/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
`timescale 1ns/1ps

module high_pitch_effect (
  input wire clk,
  input wire reset,
  input [15:0] audio_in,
  output [15:0] audio_out
);
  wire [13:0] s0;
  wire [13:0] s1;
  wire [17:0] s2;
  wire [17:0] s3;
  wire unused_counter_ovf;
  wire [15:0] unused_ram_1d;
  wire unused_add_co;
  DIG_Counter_Nbit #(
    .Bits(14)
  )
  DIG_Counter_Nbit_i0 (
    .en( 1'b1 ),
    .C( clk ),
    .clr( reset ),
    .out( s0 ),
    .ovf( unused_counter_ovf )
  );
  DIG_RAMDualAccess #(
    .Bits(16),
    .AddrBits(14)
  )
  DIG_RAMDualAccess_i1 (
    .str( 1'b1 ),
    .C( clk ),
    .ld( 1'b1 ),
    .\1A ( s0 ),
    .\1Din ( audio_in[15:0] ),
    .\1D ( unused_ram_1d ),
    .\2A ( s1 ),
    .\2D ( audio_out )
  );
  DIG_Add #(
    .Bits(18)
  )
  DIG_Add_i2 (
    .a( s2 ),
    .b( 18'b100000 ),
    .c_i( 1'b0 ),
    .s( s3 ),
    .c_o( unused_add_co )
  );
  DIG_Register_BUS #(
    .Bits(18)
  )
  DIG_Register_BUS_i3 (
    .D( s3 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( s2 )
  );
  assign s1 = s2[17:4];
endmodule
