/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
`timescale 1ns/1ps

module muffled_effect (
  input [15:0] audio_in,
  input wire clk,
  input wire reset,
  output [15:0] audio_out
);
  wire [15:0] y_1;
  wire [15:0] s0;
  wire [15:0] y_2;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire s7;
  wire s8;
  wire s9;
  wire unused_sub0_co;
  wire unused_sub1_co;
  wire unused_add0_co;
  wire unused_add1_co;
  wire unused_add2_co;
  // Sub_1
  DIG_Sub_muffled #(
    .Bits(16)
  )
  DIG_Sub_i0 (
    .a( audio_in[15:0] ),
    .b( y_1[15:0] ),
    .c_i( 1'b0 ),
    .s( s0 ),
    .c_o( unused_sub0_co )
  );
  assign s7 = s0[15];
  assign s2[11:0] = s0[15:4];
  assign s2[12] = s7;
  assign s2[13] = s7;
  assign s2[14] = s7;
  assign s2[15] = s7;
  // Add_1
  DIG_Add_muffled #(
    .Bits(16)
  )
  DIG_Add_i1 (
    .a( s2[15:0] ),
    .b( y_1[15:0] ),
    .c_i( 1'b0 ),
    .s( s3 ),
    .c_o( unused_add0_co )
  );
  // Reg_1
  DIG_Register_BUS_muffled #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( s3 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( y_1 )
  );
  // Sub_2
  DIG_Sub_muffled #(
    .Bits(16)
  )
  DIG_Sub_i3 (
    .a( y_1[15:0] ),
    .b( y_2[15:0] ),
    .c_i( 1'b0 ),
    .s( s1 ),
    .c_o( unused_sub1_co )
  );
  assign s8 = s1[15];
  assign s4[11:0] = s1[15:4];
  assign s4[12] = s8;
  assign s4[13] = s8;
  assign s4[14] = s8;
  assign s4[15] = s8;
  // Add_2
  DIG_Add_muffled #(
    .Bits(16)
  )
  DIG_Add_i4 (
    .a( s4[15:0] ),
    .b( y_2[15:0] ),
    .c_i( 1'b0 ),
    .s( s5 ),
    .c_o( unused_add1_co )
  );
  // Reg_2
  DIG_Register_BUS_muffled #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( s5 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( y_2 )
  );
  assign s9 = y_2[15];
  assign s6[11:0] = y_2[15:4];
  assign s6[12] = s9;
  assign s6[13] = s9;
  assign s6[14] = s9;
  assign s6[15] = s9;
  // Add_3
  DIG_Add_muffled #(
    .Bits(16)
  )
  DIG_Add_i6 (
    .a( s6[15:0] ),
    .b( y_2[15:0] ),
    .c_i( 1'b0 ),
    .s( audio_out ),
    .c_o( unused_add2_co )
  );
endmodule
