/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
`timescale 1ns/1ps
module DIG_Counter_Nbit
#(
    parameter Bits = 2
)
(
    output [(Bits-1):0] out,
    output ovf,
    input C,
    input en,
    input clr
);
    reg [(Bits-1):0] count;

    always @ (posedge C) begin
        if (clr)
          count <= 'h0;
        else if (en)
          count <= count + 1'b1;
    end

    assign out = count;
    assign ovf = en? &count : 1'b0;

    initial begin
        count = 'h0;
    end
endmodule

module DIG_RAMDualPort
#(
    parameter Bits = 16,
    parameter AddrBits = 4
)
(
  input [(AddrBits-1):0] A,
  input [(Bits-1):0] Din,
  input str,
  input C,
  input ld,
  output [(Bits-1):0] D
);
  reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];

  assign D = ld? memory[A] : 'hz;

  always @ (posedge C) begin
    if (str)
      memory[A] <= Din;
  end
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module reverb_effect (
  input wire clk,
  input wire reset,   
  input [15:0] audio_in, // Audio input (not too loud or else)
  output [15:0] audio_out // evertime sound loops it becomes 25% vol

);
  wire [13:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire s4;
  DIG_Counter_Nbit #(
    .Bits(14)
  )
  DIG_Counter_Nbit_i0 (
    .en( 1'b1 ),
    .C( clk ),
    .clr( 1'b0 ),
    .out( s0 )
  );
  DIG_RAMDualPort #(
    .Bits(16),
    .AddrBits(14)
  )
  DIG_RAMDualPort_i1 (
    .A( s0 ),
    .Din( s1 ),
    .str( 1'b1 ),
    .C( sys_clock ),
    .ld( 1'b1 ),
    .D( s2 )
  );
  // feedbmix
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i2 (
    .a( audio_in ),
    .b( s3 ),
    .c_i( 1'b0 ),
    .s( s1 )
  );
  // outputmix
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i3 (
    .a( audio_in ),
    .b( s2 ),
    .c_i( 1'b0 ),
    .s( audio_out )
  );
  assign s4 = s2[15];
  assign s3[11:0] = s2[15:4];
  assign s3[12] = s4;
  assign s3[13] = s4;
  assign s3[14] = s4;
  assign s3[15] = s4;
endmodule
