/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
`timescale 1ns/1ps
module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule

module DIG_Add
#(
    parameter Bits = 1
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits - 1):0] s,
    output c_o
);
   wire [Bits:0] temp;

   assign temp = a + b + c_i;
   assign s = temp [(Bits-1):0];
   assign c_o = temp[Bits];
endmodule



module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module muffled_effect (
  input [15:0] audio_in,
  input wire clk,
  input wire reset,
  output [15:0] audio_out
);
  wire [15:0] y_1;
  wire [15:0] s0;
  wire [15:0] y_2;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire [15:0] s4;
  wire [15:0] s5;
  wire [15:0] s6;
  wire s7;
  wire s8;
  wire s9;
  // Sub_1
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i0 (
    .a( audio_in ),
    .b( y_1 ),
    .c_i( 1'b0 ),
    .s( s0 )
  );
  assign s7 = s0[15];
  assign s2[11:0] = s0[15:4];
  assign s2[12] = s7;
  assign s2[13] = s7;
  assign s2[14] = s7;
  assign s2[15] = s7;
  // Add_1
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i1 (
    .a( s2 ),
    .b( y_1 ),
    .c_i( 1'b0 ),
    .s( s3 )
  );
  // Reg_1
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i2 (
    .D( s3 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( y_1 )
  );
  // Sub_2
  DIG_Sub #(
    .Bits(16)
  )
  DIG_Sub_i3 (
    .a( y_1 ),
    .b( y_2 ),
    .c_i( 1'b0 ),
    .s( s1 )
  );
  assign s8 = s1[15];
  assign s4[11:0] = s1[15:4];
  assign s4[12] = s8;
  assign s4[13] = s8;
  assign s4[14] = s8;
  assign s4[15] = s8;
  // Add_2
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i4 (
    .a( s4 ),
    .b( y_2 ),
    .c_i( 1'b0 ),
    .s( s5 )
  );
  // Reg_2
  DIG_Register_BUS #(
    .Bits(16)
  )
  DIG_Register_BUS_i5 (
    .D( s5 ),
    .C( clk ),
    .en( 1'b1 ),
    .Q( y_2 )
  );
  assign s9 = y_2[15];
  assign s6[11:0] = y_2[15:4];
  assign s6[12] = s9;
  assign s6[13] = s9;
  assign s6[14] = s9;
  assign s6[15] = s9;
  // Add_3
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i6 (
    .a( s6 ),
    .b( y_2 ),
    .c_i( 1'b0 ),
    .s( audio_out )
  );
endmodule
