/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */
`timescale 1ns/1ps

module reverb_effect (
  input wire clk,
  input wire reset,   
  input [15:0] audio_in, // Audio input (not too loud or else)
  output [15:0] audio_out // evertime sound loops it becomes 25% vol

);
  wire [13:0] s0;
  wire [15:0] s1;
  wire [15:0] s2;
  wire [15:0] s3;
  wire s4;
  wire unused_counter_ovf;
  wire unused_add0_co;
  wire unused_add1_co;
  DIG_Counter_Nbit #(
    .Bits(14)
  )
  DIG_Counter_Nbit_i0 (
    .en( 1'b1 ),
    .C( clk ),
    .clr( 1'b0 ),
    .out( s0 ),
    .ovf( unused_counter_ovf )
  );
  DIG_RAMDualPort #(
    .Bits(16),
    .AddrBits(14)
  )
  DIG_RAMDualPort_i1 (
    .A( s0 ),
    .Din( s1 ),
    .str( 1'b1 ),
    .C( clk ),
    .ld( 1'b1 ),
    .D( s2 )
  );
  // feedbmix
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i2 (
    .a( audio_in[15:0] ),
    .b( s3[15:0] ),
    .c_i( 1'b0 ),
    .s( s1 ),
    .c_o( unused_add0_co )
  );
  // outputmix
  DIG_Add #(
    .Bits(16)
  )
  DIG_Add_i3 (
    .a( audio_in[15:0] ),
    .b( s2[15:0] ),
    .c_i( 1'b0 ),
    .s( audio_out ),
    .c_o( unused_add1_co )
  );
  assign s4 = s2[15];
  assign s3[11:0] = s2[15:4];
  assign s3[12] = s4;
  assign s3[13] = s4;
  assign s3[14] = s4;
  assign s3[15] = s4;
endmodule
