// ============================================================================
// Digital Simulator Utility Modules - Shared Components
// ============================================================================
// Common building blocks generated by Digital simulator tool
// Used by multiple audio effect modules (high pitch, low pitch, reverb, etc.)
// Include this file once to avoid duplicate module declarations
// ============================================================================

// MODULE LIST
// DIG_Counter_Nbit - Up counter with clear
// DIG_RAMDualAccess - Two-port RAM (write on port 1, independent read on port 2)
// DIG_RAMDualPort - Single-port RAM (unified address for read/write)
// DIG_Add - Full adder with carry
// DIG_Sub - Full subtractor with borrow
// DIG_Register_BUS - Enabled register

// ============================================================================
// N-Bit Counter Module
// ============================================================================
// Parametrizable up-counter with enable and synchronous clear
// Used for address generation and timing control
// ============================================================================
module DIG_Counter_Nbit
#(
    parameter Bits = 2  // Counter width in bits
)
(
    output [(Bits-1):0] out,  // Current count value
    output ovf,                // Overflow flag (all bits high)
    input C,                   // Clock signal
    input en,                  // Enable: counter increments when high
    input clr                  // Clear: synchronously resets counter to 0
);
    reg [(Bits-1):0] count;
    
    // Synchronous counter logic
    always @ (posedge C) begin
        if (clr)
          count <= 'h0;              // Reset to zero
        else if (en)
          count <= count + 1'b1;     // Increment by 1
    end
    
    assign out = count;
    assign ovf = en? &count : 1'b0;  // Overflow when all bits are 1
    
    initial begin
        count = 'h0;  // Initialize to zero
    end
endmodule

// ============================================================================
// Dual-Port RAM Module (Two Independent Ports)
// ============================================================================
// True dual-port memory with independent read/write operations
// Port 1: Read/Write with separate addresses
// Port 2: Independent read with separate address
// Memory Type: Distributed RAM (implemented in FPGA LUTs, not block RAM)
// ============================================================================
module DIG_RAMDualAccess
#(
    parameter Bits = 8,       // Data width in bits
    parameter AddrBits = 4    // Address width (memory size = 2^AddrBits)
)
(
    input C,                           // Clock signal
    input ld,                          // Port 1 load enable (read enable)
    input [(AddrBits-1):0] \1A ,       // Port 1 address (write address)
    input [(AddrBits-1):0] \2A ,       // Port 2 address (read address)
    input [(Bits-1):0] \1Din ,         // Port 1 data input (write data)
    input str,                         // Port 1 store enable (write enable)
    output [(Bits-1):0] \1D ,          // Port 1 data output (read data)
    output [(Bits-1):0] \2D            // Port 2 data output (read data)
);
    // Memory array: Depth = 2^AddrBits words
    reg [(Bits-1):0] memory [0:((1 << AddrBits)-1)];
    
    // Port 1: Tri-state output when not reading
    assign \1D = ld? memory[\1A ] : {Bits{1'b0}};
    
    // Port 2: Always reads current address
    assign \2D = memory[\2A ];
    
    // Synchronous write on Port 1
    always @ (posedge C) begin
        if (str)
            memory[\1A ] <= \1Din ;  // Write data to memory
    end

endmodule

// ============================================================================
// Single-Port RAM Module
// ============================================================================
// Simple RAM with single address port for both read and write
// Used for delay lines and simple memory buffers
// Memory Type: Distributed RAM (implemented in FPGA LUTs, not block RAM)
// ============================================================================
module DIG_RAMDualPort
#(
    parameter Bits = 16,      // Data width in bits
    parameter AddrBits = 4    // Address width (memory size = 2^AddrBits)
)
(
    input [(AddrBits-1):0] A,     // Address for read/write
    input [(Bits-1):0] Din,       // Data input (write data)
    input str,                    // Store enable (write enable)
    input C,                      // Clock signal
    input ld,                     // Load enable (read enable)
    output [(Bits-1):0] D         // Data output (read data)
);
    reg [(Bits-1):0] memory[0:((1 << AddrBits) - 1)];
    
    // Read operation (conditional based on ld)
    assign D = ld? memory[A] : {Bits{1'b0}};
    
    // Synchronous write operation
    always @ (posedge C) begin
        if (str)
            memory[A] <= Din;
    end
endmodule

// ============================================================================
// N-Bit Adder Module
// ============================================================================
// Full adder with carry-in and carry-out
// Used for pointer arithmetic and accumulation
// ============================================================================
module DIG_Add
#(
    parameter Bits = 1  // Operand width in bits
)
(
    input [(Bits-1):0] a,        // First operand
    input [(Bits-1):0] b,        // Second operand
    input c_i,                   // Carry input
    output [(Bits - 1):0] s,     // Sum output (lower bits)
    output c_o                   // Carry output (overflow bit)
);
   wire [Bits:0] temp;  // Extra bit for carry
   
   // Perform addition with carry
   assign temp = a + b + {{Bits{1'b0}}, c_i};
   assign s = temp [(Bits-1):0];  // Extract sum
   assign c_o = temp[Bits];       // Extract carry-out
endmodule

// ============================================================================
// N-Bit Subtractor Module
// ============================================================================
// Full subtractor with borrow-in and borrow-out
// Used for difference calculations in filtering operations
// ============================================================================
module DIG_Sub
#(
    parameter Bits = 1  // Operand width in bits
)
(
    input [(Bits-1):0] a,        // Minuend (first operand)
    input [(Bits-1):0] b,        // Subtrahend (second operand)
    input c_i,                   // Borrow input
    output [(Bits-1):0] s,       // Difference output
    output c_o                   // Borrow output
);
    wire [Bits:0] temp;  // Extra bit for borrow
    
    // Perform subtraction with borrow
    assign temp = a - b - {{Bits{1'b0}}, c_i};
    assign s = temp[(Bits-1):0];  // Extract difference
    assign c_o = temp[Bits];      // Extract borrow-out
endmodule

// ============================================================================
// N-Bit Register Module
// ============================================================================
// Parametrizable register with enable signal
// Used for state storage and pipeline stages
// ============================================================================
module DIG_Register_BUS #(
    parameter Bits = 1  // Register width in bits
)
(
    input C,                      // Clock signal
    input en,                     // Enable: loads D when high
    input [(Bits - 1):0]D,        // Data input
    output [(Bits - 1):0]Q        // Data output (current state)
);

    reg [(Bits - 1):0] state = 'h0;  // Internal state storage
    
    assign Q = state;  // Output current state
    
    // Synchronous load when enabled
    always @ (posedge C) begin
        if (en)
            state <= D;  // Load new value
   end
endmodule
